name: "Release"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: macos-latest

    steps:
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: "v.${{ github.ref_name }}"
          draft: true
          generate_release_notes: true
